name: Auto Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from library.properties
        id: get_version
        run: |
          VERSION=$(grep '^version=' library.properties | cut -d'=' -f2)
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest semver tag
        id: latest_tag
        run: |
          LATEST=$(git tag --sort=-v:refname | grep -E '^([0-9]+\.){2}[0-9]+$' | head -n 1 || true)
          echo "Latest existing tag: $LATEST"
          echo "LATEST=$LATEST" >> $GITHUB_OUTPUT

      - name: Compare version
        id: compare_version
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          LATEST="${{ steps.latest_tag.outputs.LATEST }}"

          echo "Comparing VERSION: $VERSION with LATEST: $LATEST"

          if [ -z "$LATEST" ]; then
            echo "No existing tag found. Proceeding to tag."
            echo "PROCEED=true" >> $GITHUB_ENV
          elif [ "$VERSION" = "$LATEST" ]; then
            echo "::warning::Version $VERSION already exists. Skipping tagging."
            echo "PROCEED=false" >> $GITHUB_ENV
          elif [ "$(printf '%s\n' "$LATEST" "$VERSION" | sort -V | head -n1)" != "$LATEST" ]; then
            echo "::warning::Version $VERSION is not greater than $LATEST. Skipping tagging."
            echo "PROCEED=false" >> $GITHUB_ENV
          else
            echo "Version $VERSION is newer than $LATEST. Proceeding to tag."
            echo "PROCEED=true" >> $GITHUB_ENV
          fi

      - name: Create and push tag
        if: env.PROCEED == 'true'
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "$VERSION"
          git push origin "$VERSION"